#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root123
#      MYSQL_DATABASE: usersdb
#    ports:
#      - "3307:3306"